on:
  schedule:
    # run every 30 minutes from 6am to 11pm
    - cron: "*/30 6-23 * * *"
  # run workflow with button
  workflow_dispatch:
name: Post Changes
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      # install dependencies
      - name: Install dependencies
        run: npm install
      # run index.js
      - name: Run index.js
        run: node index.js
      # commit to github if changes are made with message as New Detections and add full timestamp
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
